### ISSUE TITLE
No download link to this tool.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DarkMatterCore/bluedump-mod#1]
Alright I have like 40 some sites pointing here saying download this tool to backup your main system default wads and I see no link ... I think its a myth if no one has given a working link.

**Comment by DarkMatterCore** [comment]
You can find the YABDM files in the "HBC" directory: https://github.com/DarkMatterCore/bluedump-mod/tree/master/HBC. This project was moved to GitHub from Google Code, so I haven't bothered to update the releases tab here (yet).

**Comment by P3rf3ctXZer0** [comment]
Thank you! Even though I already have Configurable USB loader setup and the Cioses found in the GBA temp guide installed is it still safe to use blue dump or is it more a vrigin wii u thing?

**Comment by DarkMatterCore** [comment]
You should be able to _always_ use YABDM, with or without IOS modifications. This is because the application uses the -excellent- runtimeiospatch library to apply patches on-the-fly to the running, vanilla IOS if the hardware protection is disabled. This will always be the case when you launch the application through HBC.
